// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpl5xSD0lLj_901r_dRSxxN58YdsPjq9M',
    appId: '1:139051420055:web:15f31bb0e5d7487ee49cd2',
    messagingSenderId: '139051420055',
    projectId: 'gas-tracker-ddd8b',
    authDomain: 'gas-tracker-ddd8b.firebaseapp.com',
    storageBucket: 'gas-tracker-ddd8b.appspot.com',
    measurementId: 'G-0KTX4L2BNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4aWlirDAUUVNL4h9cckJnWoFy9QE_hdU',
    appId: '1:139051420055:android:fc6c3ea5fc550a76e49cd2',
    messagingSenderId: '139051420055',
    projectId: 'gas-tracker-ddd8b',
    storageBucket: 'gas-tracker-ddd8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbo01Qxyl4aqAPryAcQpiqnZOB492IYWs',
    appId: '1:139051420055:ios:4b5f2eb9571fe75ae49cd2',
    messagingSenderId: '139051420055',
    projectId: 'gas-tracker-ddd8b',
    storageBucket: 'gas-tracker-ddd8b.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbo01Qxyl4aqAPryAcQpiqnZOB492IYWs',
    appId: '1:139051420055:ios:9b865007f0bb856de49cd2',
    messagingSenderId: '139051420055',
    projectId: 'gas-tracker-ddd8b',
    storageBucket: 'gas-tracker-ddd8b.appspot.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
